// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amwskvokvvzwnhqllgrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtd3Nrdm9rdnZ6d25ocWxsZ3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMzY3MDgsImV4cCI6MjA3MjkxMjcwOH0.FKYTWC1l-LtxGB45oGmYkEULa9dg4rZI4ztHLRaOKL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});